JAVAC=javac
SRC=./
DEST=./
FILES=RegisterAllocation.java ArmGenerator.java
FLAGS=-Xlint:-serial -sourcepath ..

all: $(FILES)
	$(JAVAC) $(FLAGS) $(SRC)$<

RegisterAllocation.java:

ArmGenerator.java:

clean:
	rm -rf **/*.class *.class
