JAVAC=javac
SRC=./
DEST=./
FILES=RegisterAllocation.java ArmGenerator.java
FLAGS=-Xlint:-serial

all: $(FILES)
	$(JAVAC) -d $(DEST) $(FLAGS) $(SRC)$<

RegisterAllocation.java:

ArmGenerator.java:

clean:
	rm -rf **/*.class
