JAVAC=javac
SRC=./
DEST=./
FILES=KNormalization.java ReductionNestedExpression.java
FLAGS=-Xlint:-serial

all: $(FILES)
	$(JAVAC) -d $(DEST) $(FLAGS) $(SRC)$<

# RegisterAllocation.java:

clean:
	rm -rf **/*.class
